var annotated_dup =
[
    [ "API", "namespaceAPI.html", [
      [ "Discord", "classAPI_1_1Discord.html", "classAPI_1_1Discord" ]
    ] ],
    [ "RSDK", "namespaceRSDK.html", [
      [ "Math", "classRSDK_1_1Math.html", "classRSDK_1_1Math" ],
      [ "Matrix", "classRSDK_1_1Matrix.html", "classRSDK_1_1Matrix" ]
    ] ],
    [ "Animator", "classAnimator.html", "classAnimator" ],
    [ "Application", "classApplication.html", "classApplication" ],
    [ "Array", "classArray.html", "classArray" ],
    [ "Audio", "classAudio.html", "classAudio" ],
    [ "Collision", "classCollision.html", "classCollision" ],
    [ "Controller", "classController.html", "classController" ],
    [ "Date", "classDate.html", "classDate" ],
    [ "Device", "classDevice.html", "classDevice" ],
    [ "Directory", "classDirectory.html", "classDirectory" ],
    [ "Display", "classDisplay.html", "classDisplay" ],
    [ "Draw", "classDraw.html", "classDraw" ],
    [ "Draw3D", "classDraw3D.html", "classDraw3D" ],
    [ "Ease", "classEase.html", "classEase" ],
    [ "Entity", "classEntity.html", "classEntity" ],
    [ "File", "classFile.html", "classFile" ],
    [ "Font", "classFont.html", "classFont" ],
    [ "Geometry", "classGeometry.html", "classGeometry" ],
    [ "HTTP", "classHTTP.html", null ],
    [ "Image", "classImage.html", "classImage" ],
    [ "Input", "classInput.html", "classInput" ],
    [ "Instance", "classInstance.html", "classInstance" ],
    [ "JSON", "classJSON.html", "classJSON" ],
    [ "Material", "classMaterial.html", "classMaterial" ],
    [ "Math", "classMath.html", "classMath" ],
    [ "Matrix", "classMatrix.html", "classMatrix" ],
    [ "Model", "classModel.html", "classModel" ],
    [ "Music", "classMusic.html", "classMusic" ],
    [ "Number", "classNumber.html", "classNumber" ],
    [ "Object", "classObject.html", "classObject" ],
    [ "Palette", "classPalette.html", "classPalette" ],
    [ "Random", "classRandom.html", "classRandom" ],
    [ "Resources", "classResources.html", "classResources" ],
    [ "Scene", "classScene.html", "classScene" ],
    [ "Scene3D", "classScene3D.html", "classScene3D" ],
    [ "SceneList", "classSceneList.html", "classSceneList" ],
    [ "Serializer", "classSerializer.html", "classSerializer" ],
    [ "Settings", "classSettings.html", "classSettings" ],
    [ "Shader", "classShader.html", "classShader" ],
    [ "SocketClient", "classSocketClient.html", null ],
    [ "Sound", "classSound.html", "classSound" ],
    [ "Sprite", "classSprite.html", "classSprite" ],
    [ "Stream", "classStream.html", "classStream" ],
    [ "String", "classString.html", "classString" ],
    [ "Texture", "classTexture.html", null ],
    [ "Thread", "classThread.html", null ],
    [ "TileCollision", "classTileCollision.html", "classTileCollision" ],
    [ "TileInfo", "classTileInfo.html", "classTileInfo" ],
    [ "Touch", "classTouch.html", "classTouch" ],
    [ "VertexBuffer", "classVertexBuffer.html", "classVertexBuffer" ],
    [ "Video", "classVideo.html", null ],
    [ "View", "classView.html", "classView" ],
    [ "Window", "classWindow.html", "classWindow" ],
    [ "XML", "classXML.html", "classXML" ]
];